### ISSUE TITLE
CSS connectivity

### ISSUE THREAD

**Issue by JackM10** [JackM10/ToDoList#1]
Can't do the Grid - CSS isn't applied to the html code

**Comment by jalaz** [comment]
I'm not sure I'm following. 
I don't see any CSS file linked to your [html](https://github.com/JackM10/ToDoList/blob/master/ToDoListMVC/Views/ToDoListMVC/Index.cshtml) 
As an alternative, you can go without CSS using just simple HTML `<table>`

**Comment by JackM10** [comment]
The link on CSS on the line [12](https://github.com/JackM10/ToDoList/blob/master/ToDoListMVC/Views/ToDoListMVC/Index.cshtml)
I want to use best practises and follow using CSS

**Comment by jalaz** [comment]
Please read [my comment](https://github.com/JackM10/ToDoList/commit/a4c4bf4064958f1856a3bd00d8b555269a3cbbdf#commitcomment-20391669)

**Comment by jalaz** [comment]
I propose to use [bootstrap](http://getbootstrap.com/getting-started/) for styling

**Comment by JackM10** [comment]
Alex, I think I need your help here)
Same problem, but I done few experiments - so current grid (that written in html using bootstrap examples) work correctly in any MVC or .NET Core project (created from VS template), but it don't want to work in mine project :(
Do you know why it happenes??
Thanks!

**Comment by jalaz** [comment]
Sure, I think you didn't follow [setup instructions](http://getbootstrap.com/getting-started/#download-cdn) carefully. They show in the example that you need two css files (`boostrap.css` and `bootsrap-theme.css`), you've connected only second one. 
Also, please move `site.css` to Content and clean it up as well.

**Comment by jalaz** [comment]
Look, I think we need code review practice. Please have a look at #7 when you have some time.

**Comment by JackM10** [comment]
Thank you!
It's work now! Adding of bootstratp-min.css to the project helps it.
Ok, I'll try to figure out Issue #7

**Comment by JackM10** [comment]
CSS and Bootstrap are moved to low priority, so now I will work more on buisness logic, closing this issue for now.

**Comment by jalaz** [comment]
why "for now"? I thought you've already resolved this one.

**Comment by JackM10** [comment]
Exactly this one - yes, but CSS in general - no, so that's why for now)

**Comment by jalaz** [comment]
OK, just seems to me a bit weird to close an issue when you what to postpone it, but it is your project, so do whatever suits you.

**Comment by JackM10** [comment]
My logic could be a little bit non standart, I close this issue because the issue is done and priority of this question in general is low. 
Once I'll back to it, I'll open new one, more targeted and specific issue
