### ISSUE TITLE
C# connectivity with html code

### ISSUE THREAD

**Issue by JackM10** [JackM10/ToDoList#2]
No idea how to connect my properties with html code (for example how to show in the grid contents of some List<>)

**Comment by jalaz** [comment]
Use [Razor](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor) for rendering your view model (VM).
In short, assuming that you have List<Todo> as your VM:

```
@model List<Todo>
<table>
   @foreach(var todo in Model)
   {
       <tr><td>@todo.Name</td></tr>
   }
</table>
```

**Comment by JackM10** [comment]
Alex, could you please assist me with null reference exception?
I can't fix it, tried to change Razor syntax, but looks like it happenes because we run project with empty List<ToDoViewModel> and I need to initialize it [https://github.com/JackM10/ToDoList/blob/master/ToDoListMVC/Views/ViewModels/ToDoViewModel.cs](url) somehow.
Thanks!

**Comment by jalaz** [comment]
The link is not working, I suspect you didn't pass the model to view. Have you tried to initialize your list and pass it to view in your controller?

**Comment by JackM10** [comment]
Here is duplicate of the link:
https://github.com/JackM10/ToDoList/blob/master/ToDoListMVC/Views/ViewModels/ToDoViewModel.cs
Yes, I initialize the list, but have no idea how th pass it to controller. I'll learn how to do it and will try to fix.

**Comment by jalaz** [comment]
It's easy, you can just use `View` helper, like this:
```
public ActionResult Todos()
{
     return View(ToDoTypeViewModel.ToDoList);
}
```

**Comment by JackM10** [comment]
Thank you!
I still didn't understand how it works, but it works now)

**Comment by JackM10** [comment]
Issue is done, I need to learn more about theory, because I didn't inderstand how the model was passes to view.

**Comment by jalaz** [comment]
it's magic of MVC :)
