### ISSUE TITLE
Remove GridViewController.cs file

### ISSUE THREAD

**Issue by jalaz** [JackM10/ToDoList#8]
[GridViewController.cs](https://github.com/JackM10/ToDoList/blob/master/ToDoListMVC/Controllers/GridViewController.cs) doesn't do anything, so I think you can just remove it.

**Comment by JackM10** [comment]
done

**Comment by jalaz** [comment]
I see the controller in your repo, please reopen

**Comment by JackM10** [comment]
Sorry, I forgot to remove it from GitHub folder, now it must be ok.
