### ISSUE TITLE
Create a dummy list of tasks in memory and render it on html view

### ISSUE THREAD

**Issue by jalaz** [JackM10/ToDoList#9]

**Comment by JackM10** [comment]
That's not a problem, and I'll do it once I'll fix of grid view.
Now I've some unformatted list, so it's hard to create tasks in it, even in html...

**Comment by JackM10** [comment]
Done in 5.0 release, but because of Issue #1 it's can't be displayed correctly.

**Comment by jalaz** [comment]
I haven't seen the list in 5.0. Just to avoid confusion the task is to create a list in C#, pass it from controller to view and render.

**Comment by JackM10** [comment]
No it's more clear task for me.
Because in 5.0 - it was just hardcoded html with Grid inside.
I'll do the List and show it in 5.3

**Comment by JackM10** [comment]
Done in 5.3 and later

**Comment by jalaz** [comment]
Since we do not apply PRs now - commented right in your commit
